### ISSUE TITLE
impl tokio::io::AsyncRead/Write for RequestStream?

### ISSUE THREAD

**Issue by doraneko94** [hyperium/h3#111]
I wanted to use `tokio::io::copy` against `RequestStream`, but it does not seem to implement `tokio::io::AsyncRead` and `tokio::io::AsyncWrite`.
Do you intend to implement these in the future?
If you intend to do so, I can attempt to fix them. Then, do you have any implementation policies or tips?

**Comment by seanmonstar** [comment]
Most likely not. A request stream can send other frames besides just data. It shouldn't be too complicated to make an adapter outside of the crate, though.
