### ISSUE TITLE
Trait bounds of h3::server::RequestStream::recv_trailers()

### ISSUE THREAD

**Issue by eagr** [hyperium/h3#140]
```rs
impl<S, B> RequestStream<S, B>
where
    S: quic::RecvStream + quic::SendStream<B>,
    B: Buf,
{
    /// Receive an optional set of trailers for the request.
    pub async fn recv_trailers(&mut self) -> Result<Option<HeaderMap>, Error> {
        let res = self.inner.recv_trailers().await;
        if let Err(ref e) = res {
            if e.is_header_too_big() {
                self.send_response(
                    http::Response::builder()
                        .status(StatusCode::REQUEST_HEADER_FIELDS_TOO_LARGE)
                        .body(())
                        .expect("header too big response"),
                )
                .await?;
            }
        }
        res
    }
}
```

When the user needs to use both `recv_data()` and `recv_trailers()`, they have to consume a `RequestStream<quic::RecvStream + quic::SendStream<B>>`. The problem is they also need to use the stream to send a response to the peer. For that to work, they may need to either clone the stream (unnecessary) or pass the reference around (need to deal with lifetime, problematic).

Also, I think the function may be doing too much. We probably don't need to handle this error as a special case (not doing anything special with it anyway). It's probably better to be handled in the upper layer along with other errors.

With that handling out of the picture, we could change the bound to `S: quic::RecvStream`. Then the user could simply split the stream and avoid the problems above.

**Comment by seanmonstar** [comment]
> I think the function may be doing too much. We probably don't need to handle this error as a special case (not doing anything special with it anyway). It's probably better to be handled in the upper layer along with other errors.

Makes sense to me, especially since these are trailers, and the user may have already sent response headers.
