### ISSUE TITLE
How  to send data by h3-quinn

### ISSUE THREAD

**Issue by sunnyregion** [hyperium/h3#141]
I want to send data by body.

The http::Request::builder()'s body  must empty.

I  send data  by stream.

It is run ok,not any error. But Server can not receive.

under code:

 let mut  request=http::Request::builder().method("POST")
                 .uri(dest)
                 .header("X-Custom-Foo", "Bar").body(())?;
            request.headers_mut().append("User-Agent", http::header::HeaderValue::from_static("cloudminds-agent/1.0"));
            let s=opt.data.clone();
            // let s= Box::leak(s.into_boxed_str());
            request.headers_mut().append("Param-Data",http::header::HeaderValue::from_str(&s).unwrap());
            eprintln!("data:{}",opt.data);
            let mut stream = send_request.send_request(request).await?;
            match stream.send_data(hyper::body::Bytes::from("helllo")).await{
                Ok(_) => {
                    eprintln!("💯  Request to connection successful");
                }
                Err(err) => {
                    eprintln!("Unable to send response to connection peer: {:?}", err);
                }
            };

stream.finish().await?;

**Comment by eagr** [comment]
Try calling `stream.finish()` after `send_data()`. `send_data()` basically just writes data to the buffer, doesn't actually send anything.

**Comment by sunnyregion** [comment]
> Try calling `stream.finish()` after `send_data()`. `send_data()` basically just writes data to the buffer, doesn't actually send anything.

Maybe I misunderstood.
So that's how it's done：`stream.finish()` after `send_data()`.

**Comment by sunnyregion** [comment]
A request stream can send other frames besides just data.

**Comment by sunnyregion** [comment]
The client run `send_data` is correct. Server maybe is not correct.

**Comment by eagr** [comment]
I just double checked. I think you do need to call `finish()` to actually send the data. But you don't have to take my words for it. Just dig into h3-quinn to see how it works yourself. 😄
