### ISSUE TITLE
quiche

### ISSUE THREAD

**Issue by zhangbtciab** [hyperium/h3#147]
when h3 can support quiche?

**Comment by inflation** [comment]
`quiche` has its own http3 implementation. Furthermore, that project doesn't design with async Rust in mind. Technically, you could roll your own adapter using primitives, but it's a daunting process. Checkout `h3-quinn` and `s2n-quic-h3` for examples of such code.

**Comment by eagr** [comment]
`quiche` seems to distinguish bidi- and uni- streams by the stream id. So essentially, there is one kind of stream in `quiche`. That may not map well to the `h3::quic` traits, esp. the *"splittable"* bidi-stream.

And `quiche` is strongly tied to and probably works best with its own h3 module. Curious, any particular reasons you prefer to to use hyper/h3 + quiche?

**Comment by eagr** [comment]
Got something being hacked out in this repo [h3-quiche](https://github.com/eagr/h3-quiche), if you're still interested. Just an experiment, nothing promised. Implementing this is actually smoother than I thought.

**Comment by eagr** [comment]
Done experimenting on gluing h3 w/ quiche. A quiche stream can be used via the combination of a connection and a stream id, but the streams **cannot be accessed publicly**. So we may have to vendor the source code of quiche to properly implement the `h3::quic` traits.

If your goal is to use hyper w/ quiche, a much more viable option I see would be to try to glue `quiche/h3` (the quiche HTTP/3 implementation) with hyper.
