### ISSUE TITLE
how can I upload a file with h3?

### ISSUE THREAD

**Issue by zhangbtciab** [hyperium/h3#149]

**Comment by seanmonstar** [comment]
If you want to use `h3` specifically, you could look at the `examples/client.rs` file that sends a GET request, and adjust it to sent a POST/PUT, and send a body.

Another alternative is to try out [reqwest's unstable HTTP/3 support](https://docs.rs/reqwest/latest/reqwest/#unstable-features), and use the normal request builder to upload a file, and let reqwest do the HTTP/3 stuff for you.
