### ISSUE TITLE
Remove nightly tests from CI?

### ISSUE THREAD

**Issue by eagr** [hyperium/h3#154]
Compiling tests against nightly Rust sometimes fails. We could choose to ignore it, but if it fails before other tests finish, it would cancel other tests.

If there's no particular reasons that we want to build/test against nightly, it seems better to remove them, at least, not let them run on a per-pr basis.

**Comment by seanmonstar** [comment]
Looks like nightly is used in a few CI jobs:

- docs for `-D intra-doc-link-resolution-failure`
- fuzz, I'm not sure why

It would be required to add a [minimal-versions](https://doc.rust-lang.org/cargo/reference/unstable.html#list-of-unstable-features) check, which I've at least wanted to add to hyper.

I do agree that blocking PRs on nightly, which can have its own bugs, is not great. We could pin to specific nightly versions that we know are good, and update it periodically. That's what Tokio does.

**Comment by eagr** [comment]
Sorry if I wasn't being clear enough. I myself always use nightly for fmt and clippy (and maybe doc), as nightly has the latest rules, and they rarely break even on the latest nightly.

I was proposing to remove nightly for builds and tests. As I understand, compiling against nightly are more about helping to find bugs in the compiler rather than in h3. So I guess they probably shouldn't be run on every pr, right?

**Comment by Ruben2424** [comment]
The current Compiler error in nightly, is this something to report to the compiler? I have no idea how to simply reproduce this elsewhere.

**Comment by eagr** [comment]
It's nice to do it. We may need to provide some distilled/minimized example code for reproduction.
