### ISSUE TITLE
push ids are not stream ids

### ISSUE THREAD

**Issue by FlorianUekermann** [hyperium/h3#174]
The stream id type is used to represent and validate push ids. On GOAWAY frames from the client, `StreamId::is_push()` is used to validate the push id. Based on my understanding of the RFC I believe this is incorrect (they are not related) and it leads to errors on client initiated shutdowns:
```
h3::Error { code: H3_ID_ERROR, reason: "non-push StreamId in a GoAway frame: client bidirectional stream 0" }
```
I can send a PR with the following changes:
- add a PushId type
- Either:
  - differentiate Frame::ServerGoaway(StreamId) and Frame::ClientGoaway(PushId)
  - introduce `GoawayId` with stream and push variants for Frame::Goaway(GoawayId)
  - use Frame::Goaway(u64) and convert to respective type as soon as possible after unpacking

**Comment by Ruben2424** [comment]
Thanks for submitting this issue.
You are right. This does not look correct. 

In my opinion your second suggestion with the `GoawayId` is the best.
Since server push is not fully implemented yet the server can not push. So the only valid push id for now is 0 right?

**Comment by FlorianUekermann** [comment]
> Since server push is not fully implemented yet the server can not push. So the only valid push id for now is 0 right?

Not quite. GOAWAY frames sent by the remote party have no upper bound on the push id they specify afaik. Specifying a larger one won't be meaningful in the absence of server pushes , but is valid.

I'll have a look at this and try to  send a PR asap.
