### ISSUE TITLE
How to create customed WebtransportSession

### ISSUE THREAD

**Issue by chrislearn** [hyperium/h3#195]
I want to create my customed WebtransportSession struct instead of using the WebtransportSession in h3_webtransport.

I found it is hard to reuse code in h3_webtransport for many struct has private new function. Is it possible public these new function?

Thanks

**Comment by seanmonstar** [comment]
Is there something small we can open up that would let you use it? In general many of the internals are private so that we can change them in the future.

But we do want to be flexible where it is reasonable.

**Comment by seanmonstar** [comment]
Closing for now. But if you or anyone else has requests for making things possible, you're welcome to ask! It's easier if we know a use case and can keep as much internals as possible private.
