### ISSUE TITLE
Client request sending

### ISSUE THREAD

**Issue by stammw** [hyperium/h3#20]
Implement the `client::Connection` `send_request()` and `poll_ready()` methods.

`send_request()` will:
 - Convert `http::Request` to an `h3` specific `Header`
 - Encode this header with `QPACK` (in a stateless fashion for the moment, no dynamic table)
 - Open a `quic` bidirectional stream
 - Send the header on this stream
 - Return a `client::RequestStream<T::BidiStream, B> where T: quic::Connection<B>, B: Buf`

Let's address this `RequestStream` implementation in a later work, once server is able to receive and decode the header in order to emit a `server::RequestStream`.

**Comment by seanmonstar** [comment]
Done in #23
