### ISSUE TITLE
h3_webtransport datagrams high packet loss at 500kb/s per session

### ISSUE THREAD

**Issue by cybersoulK** [hyperium/h3#209]
I have very high packet loss with my implementation.

I also see that session has a lifetime, so currently i am using a tokio select, which is not ideal.

the following method might lead to the freezing/packet loss that i am experiencing

this is the h3_webtransport::server::WebTransportSession::send_datagram:
```rust
/// TODO: maybe make async. `quinn` does not require an async send
pub fn send_datagram(&self, data: B) -> Result<(), Error>
```

**Comment by seanmonstar** [comment]
@darioalessandro or @ten3roberts may know better?

**Comment by ten3roberts** [comment]
Hmm, that is odd that you are experiencing data loss.

The send_datagram just uses quinn (or your selected backend) to send the datagram with a VarInt prefix in the payload.

What are you sending?

**Comment by cybersoulK** [comment]
@ten3roberts
> What are you sending?

i am mostly sending positional data that fills up to the max_datagram_size.

ok i think i found the issue, i get a bunch of these errors:
Err(h3::Error { kind: TooLarge, code: : None }) . data_len: 1422 . max_packet_size: 1422

it drops the package if bytes_len is equal to max_packet_size?
and in the worst case, shouldn't the server fragment and have the client reassemble them, even if data_len surpassed max_packet_size?


i am also having a seperate (maybe related?) issue where the server inbound becomes frozen, but i am doing more testing to get a plausible cause

**Comment by cybersoulK** [comment]
yeah so that's an issue. why does a datagram needs a stream_id with 8 bytes proceeding the payload?
if this is really necessary, then at least implement the max_datagram_size on h3_connection to subtract 8 bytes.
I can temporary subtract myself, but i don't see an average user might not realize that.

**Comment by cybersoulK** [comment]
After extensive testing, manually subtracting 8 works as it should. But i have not been able to narrow down the client->server datagram delay. Sometimes reaches 5 seconds delay. Chrome on mac works perfectly as it should. Everything else is terrible: Firefox on mac and Chrome+firefox on windows.

How could this be? how can the inbound overhelm the outbound on clients? i am trying hard to find a mishandling of async in the client, but i can't find it for hours.

**Comment by darioalessandro** [comment]
@cybersoulK in my experience the best way to fix these kind of issues is to create a minimal setup that allows us to reproduce the issue, @cybersoulK would you be interested in creating this for us?

**Comment by cybersoulK** [comment]
hey guys, i used sharkwire, and i finally identified the error. It doesn't look like it's h3_server or the web_sys implementation of Webtransport, but some other behaviour on how the browser handles the packet transmission. 

```rust
fn send_datagram<M: Message + 'static>(connection: Rc<RefCell<WebTransport>>, data: Vec<u8>) {

    let datagrams = connection.borrow_mut().datagrams();
    let writer = datagrams.writable().get_writer().unwrap();

    let data = Uint8Array::from(data.as_slice());
    let _ = JsFuture::from(writer.write_with_chunk(&data));

    writer.release_lock();
}
```

the packets are all processed before rendering the graphics with this function.
It looks like they are queued by webtransport, is there a way to force flush this queue? or perhabs it's necessary to have webtransport in a web worker for it to work properly?

I spent the entire day digging into codes and experimenting, so hopefully pays out now!

**Comment by cybersoulK** [comment]
i will close for now, since my evidence concludes that h3_server is good.
But i still suggest to do something about max_datagram_size, since it's not clear to the user that he needs to subtract 8 bytes manually.

**Comment by cybersoulK** [comment]
https://github.com/w3c/webtransport/issues/543
