### ISSUE TITLE
When h3 crate can be prod ready?

### ISSUE THREAD

**Issue by taikulawo** [hyperium/h3#265]
Hi, all

We are looking for rust h3 lib to add http/3 support for our gateway. On early gray version, there will be 1,000,000 qps http/3.
Does h3 has plan to will be prod ready?

**Comment by seanmonstar** [comment]
The goal is for this library to be usable for anything, yes. Most key features work. If you prefer to use something like h3, you can try it now. If you prefer for `hyper` to make it easier to use, that is in the proposed [ROADMAP](https://github.com/hyperium/hyper/pull/3763).
