### ISSUE TITLE
Send GREASE

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/h3#28]
The spec recommends ("SHOULD") exercising peer implementations to ensure that they can handle new features when they come out. This is done by sending random settings, stream and frame types (that fit the `0x1f * N - 0x21` scheme). We should do that by default, with an option to disable it.

- Sending a GREASE setting
- Opening a GREASE stream type
- Sending a GREASE frame on every stream

**Comment by Ruben2424** [comment]
I didn't found this in the newest spec. Is this still relevant?

**Comment by seanmonstar** [comment]
[From the spec regarding SETTINGS](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-7.2.4.1):

> Setting identifiers of the format `0x1f * N + 0x21` for non-negative integer values of N are reserved to exercise the requirement that unknown identifiers be ignored. Such settings have no defined meaning. Endpoints SHOULD include at least one such setting in their SETTINGS frame.

Regarding [stream types](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-6.2.3):

> Stream types of the format `0x1f * N + 0x21` for non-negative integer values of N are reserved to exercise the requirement that unknown types be ignored. These streams have no semantics, and can be sent when application-layer padding is desired. They MAY also be sent on connections where no data is currently being transferred.

And [frame types](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-7.2.8):

> Frame types of the format `0x1f * N + 0x21` for non-negative integer values of N are reserved to exercise the requirement that unknown types be ignored ([Section 9](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#extensions)). These frames have no semantics, and MAY be sent on any stream where frames are allowed to be sent.

-----

So only the note about reserved SETTINGS includes the language that an implementation SHOULD send these. The others don't have such strong language. I noticed that https://github.com/cloudflare/quiche includes a `grease` option that will try to send all 3 of these.

**Comment by Ruben2424** [comment]
Ok, I will try to implement that.
