### ISSUE TITLE
Document all the public API

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/h3#34]
We should add `#![deny(missing_docs)]` to the top of the `h3` crate, and document all the types and methods that the lint catches.

**Comment by stammw** [comment]
We should also use this opportunity to reorder the modules so they are similar to `h2` and `hyper`:

```rust
use std::*;

use external_crate::*

use crate::*;

/// Doc Foo
struct Foo {}

/// Doc Bar
enum Bar {}

// --- impl Foo
impl Foo {}

impl Baz for Foo {}

// --- impl Bar
impl Bar {}

impl Quux for Bar {}
```
