### ISSUE TITLE
send/receive body

### ISSUE THREAD

**Issue by FrankSpitulski** [hyperium/h3#48]
what is the recommended way to send and receive a request body?

I've tried the following, but it seems suboptimal.

the library appears to hardcode () as the body type, so I tried using the send and recv streams.
from the server side's send_data I keep getting the NotReady error if there is any latency. without any interface to wait until it's ready I'm forced to do a spin loop until it goes through.
from the client side's recv_data reading too quickly will cause None to be returned, but there also doesn't seem to be a good way to tell if the stream has been closed/finished other than that same None response. this is exactly the same strategy as the example provided https://github.com/hyperium/h3/blob/master/examples/client.rs#L69.

**Comment by seanmonstar** [comment]
For sending, the goal is that you can call `send_data(buf).await` and that's it. It should await until the connection could send more data. The server example shows sending file data.

Receiving should work as shown in the example. A `None` implies the stream has ended. 

Do you have some example code that you could show us?

**Comment by FrankSpitulski** [comment]
sure. I've uploaded it to a fork.

https://github.com/FrankSpitulski/h3/tree/test/fileserver/examples

create some large file in the cwd

run the server with run --release --package examples --example server -- selfsigned

run the client with run --release --package examples --example client -- https://localhost:4433?file=${FILE}

if you introduce any sort of latency to the client, for example by running them on different systems, you'll start triggering the send retries in the server (since it's getting that NotReady error) and very frequently if the client was faster than the server the recv function in the client will prematurely return None which will cause the client to stop reading.

**Comment by FrankSpitulski** [comment]
> The server example shows sending file data.
A filesearch of the server example shows no use of send_data, did I miss it?

**Comment by seanmonstar** [comment]
No, I apparently remembered incorrectly. It's not in there at all. I thought it was a file server example.

**Comment by seanmonstar** [comment]
Well, I'd say that it doesn't work the way I described in some circumstances should be considered a bug. The async functions *should* handle waiting for when the stream is ready to send or receive data. A user shouldn't have to do any extra dance.

I can try to take a look in a week or two. Or, well, would you like to try to dig in and help correct it?

**Comment by FrankSpitulski** [comment]
Sure I can have a look.

**Comment by FrankSpitulski** [comment]
from what I can tell it's timing related since I can't repro it 100%. my guess is some other thread is calling send_data while another is still calling poll_ready. are there any spots you could point out where this could happen? I can't seem to repro in a debugger to walk up the stack.

**Comment by FrankSpitulski** [comment]
with respect to the client recv_data terminating early, it's because it delegates to the frame stream's poll_data which returns early if `self.remaining_data == 0`. Should it instead wait for the trailers (as it does now) or a stream finish (as it does not do now?)?

**Comment by FrankSpitulski** [comment]
I think the issue may stem from calling send_data from the server twice (or more), one after the other to serve the file in chunks. It looks like it is intended to only be used once per request.

**Comment by stammw** [comment]
@FrankSpitulski Thanks for reporting this! I'll have a look into it in the next few days.

**Comment by stammw** [comment]
So there is effectively a big flaw into the implementation: `NotReady` should not exist as `poll_ready()` should actually return `Poll::Pending` in that case.

**Comment by stammw** [comment]
Looking a bit further into it, it appears that things start to get nasty when `poll_ready()` returns its first `Poll::Pending`. On the next poll, the h3-quinn impl calls `ready!(self.stream.write_all(data.chunk()).poll_unpin(cx))?;` again. Which seems to trigger an invalid write. 

@seanmonstar As you mentioned in the design document, `SendStream::poll_ready()` should probably be `Pin<>` ?

**Comment by seanmonstar** [comment]
I don't think a `Pin` will let you do what you want, the lifetimes will still be weird. You could just use a loop there (maybe even using `AsyncWrite::poll_write`), and advance the buf until it's empty.

**Comment by stammw** [comment]
Yes, I've been trying to store a `quinn::WriteAll<'a>` future inside of a `h3_quinn::SendStream` and it looks like propagating the lifetime makes it very hard to get valid code everywhere, if not even impossible. I started trying to use `AsyncWrite`, but for now the bug is still there...

**Comment by seanmonstar** [comment]
Something like this should work, no?

```rust
if let Some(ref mut buf) = self.writing {
    while buf.has_remaining() {
        let n = ready!(Pin::new(&mut self.stream).poll_write(cx, buf.chunk()))?;
        buf.advance(n);
    }
}
```

**Comment by stammw** [comment]
It seems like this solves the problem, thanks @seanmonstar !

@FrankSpitulski can you confirm this bug is gone rebasing your code on [this branch](https://github.com/hyperium/h3/tree/fixes/stammw%2Fquinn-write-future) ?

Still, the client doesn't react appropriately when the problem occurs: it should terminate on error because of an invalid `Data` frame reception. With the test I'm running, the client hangs forever. The files i've generated come from `/dev/zero`, maybe data frames of size `0` should throw an error?

Should I push a little further and try to write unit tests for this ? Or could we open an issue and reproduce this later?

**Comment by FrankSpitulski** [comment]
I ran it a few times and the issue did not appear. Looks like this solves it.

**Comment by seanmonstar** [comment]
@stammw wanna make a PR with the fix in that branch?

**Comment by stammw** [comment]
I'll do as soon as I get back from holidays :) (tomorrow)
