### ISSUE TITLE
What is the health/status of this project?

### ISSUE THREAD

**Issue by matthew-russo** [hyperium/h3#49]
Hello,

I was curious what the general status/health of this project was -- I see it hasn't been committed to in a few months, has no README or docs and isn't published on crates (https://crates.io/crates/h3, https://crates.io/crates/h3-quinn).

I was looking in to quinn and found this issue: https://github.com/quinn-rs/quinn/issues/1085 which talks about moving the h3 implementation to this repo and quinn-h3 no longer exists in the quinn repo as of this commit (https://github.com/quinn-rs/quinn/commit/07377c6af39b0738a5c3167a0cba718a88762e0f) so just wanted to check in and make sure this repo is / will still be the home of the http3-quinn integration

Thanks

**Comment by stammw** [comment]
Hello Mattew,

Yes this project is still in progress, It advances quite slowly as I didn't have much energy to put in lately. Hopefully, this will change in the next weeks and it will get more traction to reach a MVP: be able to integrate into hyper.

The goal of this project is not only to offer an http3-quinn implementation, but also to bring an interface so other QUIC stack can be used underneath, via the traits in [h3/src/quic.rs](https://github.com/hyperium/h3/blob/master/h3/src/quic.rs).

I'm not aware whether other HTTP3 over Quinn projects are ongoing.

**Comment by matthew-russo** [comment]
Thank you! I was more concerned with direction than pace -- I totally understand that development may be slow. I'll see if there are any contributions I can make as well.

**Comment by stammw** [comment]
Thanks! Contributions would be more than appreciated ! I'll try to come up with some issues to start with. Don't hesitate to bring your own contribution ideas though.

**Comment by seanmonstar** [comment]
We'd be happy to have you! I'll be distracted for a couple more weeks, focusing on trying to get the [Tokio Console](https://github.com/tokio-rs/console) "launched", and then I expect to pick back up here some more. I at least plan to add a bit more tests. I'll also be able to spend some time fleshing out some more issues.

But I don't want to imply you or anyone else needs to wait! I'd be happy to work with you in an issue or Discord to figure out how to get started. <3
