### ISSUE TITLE
Test h3-quinn stream read reordering impl

### ISSUE THREAD

**Issue by stammw** [hyperium/h3#5]
The QUIC-traits impls with `quinn` polls data from the transport layer in an unordered fashion:
we get `(u64, Bytes)` chunks, the first member being the offset in the stream for that data.

I've quickly thrown a reordering implementation that would surely need a little testing effort.
Decoupling the reordering impl should also make micro-benchmarking possible at this level, which 
would be nice.

In `h3-quinn/src/lib.rs`:

```rust 
impl<S: Session> quic::RecvStream for QuinnRecvStream<S> {
    fn poll_data(
        &mut self,
        cx: &mut task::Context<'_>,
    ) -> Poll<Result<Option<Self::Buf>, Self::Error>> {}
}
```

**Comment by seanmonstar** [comment]
For now, in #29 we resorted to using quinn's `read` which preserves order, but requires an extra copy. I've opened https://github.com/quinn-rs/quinn/issues/929 to see about getting a `recv_ordered`, which preserves ordering without the copy.
