### ISSUE TITLE
Variable-length integer dependency

### ISSUE THREAD

**Issue by stammw** [hyperium/h3#6]
H3 uses the same [integer representation] as QUIC in various places: frame headers, stream types.
In short, it is a size-hint prefixed integer representation that can weight from 1 to 8 bytes.

We need to choose how to implement this in `h3`:
* Develop our own thing: to me that would create effort duplication.
* Use the `quinn`'s impl directly: This is how it is done in `quinn-h3` right now.
* Extract a crate from `quinn`: 
  * Here are [the doc] and [the implementation].
  * Would `quinn` maintainers be OK to do this, and depend on it? @djc, @Ralith ?
  * Where should we put this ?

[integer representation]: https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#integer-encoding
[the doc]: https://docs.rs/quinn/0.6.1/quinn/struct.VarInt.html
[the implementation]: https://github.com/djc/quinn/blob/master/quinn-proto/src/varint.rs

**Comment by djc** [comment]
Seems to me like duplicating this code is the right way forward. Extracting it out into a separate crate seems silly since it's (a) not a large amount of code and (b) doesn't see a lot of churn.

**Comment by stammw** [comment]
closed via #12
