### ISSUE TITLE
Connection Pooling

### ISSUE THREAD

**Issue by FrankSpitulski** [hyperium/h3#69]
Hi @stammw, the recent changes with the h3::Client and SendRequest have made it difficult to pool quic connections. The client takes ownership of the connection, which would ordinarily be fine since we could just pool the clients, but it also returns a second future that needs to be polled to drive the connection to completion. This design seems to push towards creating a new connection + client for every request. Is that intended? If not, perhaps the examples module could include an example of connection reuse.

**Comment by stammw** [comment]
Hi Frank,

I'm not sure to fully understand what you are trying to achieve, but using one connection to run multiple requests is clearly an important goal for HTTP/3 and thus for this crate.

If you need to send multiple requests sequentially, you can use the same `SendRequest` instance for each requests like so:

```rust
let (mut driver, mut send_request) = h3::client::new(quinn_conn).await?;

let drive = async move {
    future::poll_fn(|cx| driver.poll_close(cx)).await?;
    Ok::<(), Box<dyn std::error::Error>>(())
};

let requests = async move {
    // First request
    let mut stream = send_request
        .send_request(http::Request::get("/foo").body(())?)
        .await?;
    stream.finish().await?;
    let resp = stream.recv_response().await?;
    while let Some(mut chunk) = stream.recv_data().await? {}

    // Second request
    let mut stream = send_request
        .send_request(http::Request::get("/bar").body(())?)
        .await?;
    stream.finish().await?;
    let resp = stream.recv_response().await?;
    while let Some(mut chunk) = stream.recv_data().await? {}
};

tokio::join!(requests, driver);
```

If you want to run them concurrently, you can `Clone` the `SendRequest` instance and use them in multiple futures.

```rust
let (mut driver, mut send_request1) = h3::client::new(quinn_conn).await?;

let drive = async move {
    future::poll_fn(|cx| driver.poll_close(cx)).await?;
    Ok::<(), Box<dyn std::error::Error>>(())
};

let send_request2 = send_request1.clone();

let request1 = async move {
    // First request
    let mut stream = send_request1
        .send_request(http::Request::get("/foo").body(())?)
        .await?;
    stream.finish().await?;
    let resp = stream.recv_response().await?;
    while let Some(mut chunk) = stream.recv_data().await? {}
}

let request2 = async move {
    // Second request
    let mut stream = send_request2
        .send_request(http::Request::get("/bar").body(())?)
        .await?;
    stream.finish().await?;
    let resp = stream.recv_response().await?;
    while let Some(mut chunk) = stream.recv_data().await? {}
};

tokio::join!(request1, request2, driver);
```

If you want all that to run in parallel, take a look at `tokio::spawn()`.

If that doesn't answer your question, can you write a small example of what you are trying to do ?

**Comment by FrankSpitulski** [comment]
What about the case where you want to send a request, wait, then send another request using the same connection? That's difficult because the driver is already polled to completion when you send the first request.


```
let (mut driver, mut send_request) = h3::client::new(quinn_conn).await?;

let drive = async move {
    future::poll_fn(|cx| driver.poll_close(cx)).await?;
    Ok::<(), Box<dyn std::error::Error>>(())
};

// get info from the first server
let request1 = async move {
    // First request
    let mut stream = send_request
        .send_request(http::Request::get("/foo").body(())?)
        .await?;
    stream.finish().await?;
    let resp = stream.recv_response().await?;
    while let Some(mut chunk) = stream.recv_data().await? {}
};

tokio::join!(request1, driver);
doProcessingBasedOnFirstRequest();

// send data back to first server on same connection
let request2 = async move {
    // Second request
    let mut stream = send_request
        .send_request(http::Request::get("/bar").body(())?)
        .await?;
    stream.finish().await?;
    let resp = stream.recv_response().await?;
    while let Some(mut chunk) = stream.recv_data().await? {}
}

tokio::join!(request2, driver /* driver already polled */);

```

**Comment by stammw** [comment]
You can either use `tokio::select! {}` to get the driver back once the first request is completed:

```rust
let (mut driver, mut send_request) = h3::client::new(quinn_conn).await?;

// Note the `Box::pin()` usage, so driver gets to be reuasble after `select!` by implementing `Unpin`
let mut drive = Box::pin(async {
    future::poll_fn(|cx| driver.poll_close(cx)).await?;
    Ok::<(), Box<dyn std::error::Error>>(())
});

// `send_request` is captured by reference here, so we can reuse it for the next request
let request1 = async { request1_exec(&mut send_request).await? }

// `request1` should resolve first if there is no connection-level error
let request1_result = tokio::select! {
    r = request1 => r?,
    drive = &mut drive => drive?,
};

// Here, `send_request` is moved into the closure so it is dropped once the request completes.
// If not, `drive` will never resolve.
let request2 = async move { request2_exec(&mut send_request, request1_result).await? }

tokio::join!(request2, drive);
```

Note that the `request1` resolve return value won't be the same as `drive` one, so you will have to find your way to handle this. Take a look at the excelent [tokio documentation](https://docs.rs/tokio/1.15.0/tokio/macro.select.html) for some examples.

Or, you can `spawn` the driver and wait for its completion at the end of `main()`:

```rust
let (mut driver, mut send_request) = h3::client::new(quinn_conn).await?;

let drive = tokio::spawn(async move {
    future::poll_fn(|cx| driver.poll_close(cx)).await?;
    Ok::<(), Box<dyn std::error::Error + Send>>(())
});

// `send_request` is captured by reference here, so we can reuse it for the next request
let request1_result = request1_exec(&mut send_request).await?;
request2_exec(&mut send_request, request1_result).await?;

drop(send_request);
drive.await?.unwrap();
```

TIP: don't forget to tell Markdown for which language it should higlight your code blocks by using:

```
 ```rust
 // your code here
  ` `` 
```

**Comment by FrankSpitulski** [comment]
Thanks. I can pool a tuple of send_request and a joinhandle containing the driver future. it's still a bit strange to have the driver outside and need to wait on both futures. why is it done that way?

**Comment by stammw** [comment]
Yes I know it can be surprising.

Polling the driver from inside wouldn't let the user choose how the it should be handled. A simple case being: if we spawn a driver internally, then the crate can no longer be executor agnostic. This is a low level crate, its purpose is to be integrated into Hyper or Actix, so they offer HTTP/3 along with other versions.

There need to be a driver because HTTP/3 defines streams that should be managed for the whole connection life-time. See the [HTTP/3 draft](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-control-streams) to understand why. 

A server is always polled, so we don't need to poll a driver separately. For the clients on the other hand, we cannot be sure that at least one request is running. And even if there is, which request should drive the connection?

The answer is a bit long, but I hope that helps !
