### ISSUE TITLE
"BufList" dependency choice

### ISSUE THREAD

**Issue by stammw** [hyperium/h3#7]
Most of the code I've laid out in `quinn-h3` is based on `tokio_util::codec` and its `AsyncRead` friend. The problem with them is that it introduces a mandatory copy in it's user buffer for all data (through the `&[u8]` param).

@seanmonstar's proposal introduces a `Bytes`-like yielding stream read API:

```rust
// src/quic.rs
pub trait RecvStream {
    /// The type of `Buf` for data received on this stream.
    type Buf: Buf;

    fn poll_data(
        &mut self,
        cx: &mut task::Context<'_>,
    ) -> Poll<Result<Option<Self::Buf>, Self::Error>>;
}
```

Cool, now we can be zero-copy from transport to user! But now, we'd like to decode frames on something like `impl Buf for &[Bytes]`.

Sean pointed out that he already [implemented it] in `hyper`. So we could: 
* Copy the implementation in `h3`
* Depend on hyper
* Move that to a crate. 

My opinion is that it has its place in `tokio_util`, and that a `FrameRead` implementation based on it would be very useful for the whole ecosystem, aside the fact that we wouldn't have to run our own thing in `h3`.

[implemented it]: https://github.com/hyperium/hyper/blob/master/src/common/buf.rs

**Comment by seanmonstar** [comment]
The implementation in hyper is tiny, I'd just copy it directly to h3 to start with. It *would* be nice to update `tokio_util::codec`, but I think a deeper redesign of that module is required, and don't want to block us here.

**Comment by stammw** [comment]
Closing via #14
