### ISSUE TITLE
Documentation / project status

### ISSUE THREAD

**Issue by euberdeveloper** [hyperium/h3#70]
Hi, I am using Quinn for a project and I would also like to add http/3 to both a server and a client written in Rust.

I would like to know if the project is ready (maybe not stable but usable) and if there is any documentation or tutorial or I would have to inspect the source code or the tests to use it

Sorry to write an issue because of this, but I think that at least the lack of a short description in the readme can be considered enough for an issue

**Comment by stammw** [comment]
Hi @euberdeveloper, thanks for your interest in the project.

Yes, I realize that landing on the repo with no README at all can make one feel the project is not active. I plan to redact one along with the API documentation very soon.

The crate is usable, and it should interoperate decently with most of the other implementations out there. 

For the moment, there is no documentation or tutorial. But a good starting point for you would be the examples in `examples/`. Let me know if I can be of any help if you start trying to implement something.

Opening an Issue is totally justified for this matter. Right now, I'm working on graceful shutdowns, and I should be preparing the crate for a first release just after that. See the [v0.1 milestone](https://github.com/hyperium/h3/milestone/1) about this.

**Comment by Pascualex** [comment]
Hi, I'm trying to build a server that supports WebTransport clients, which is a use case that might become more popular with the release of WebTransport in Chrome 97.

Good to know that v0.1 isn't far away, keep up the good work!

**Comment by stammw** [comment]
Hi @Pascualex.

Nice to know you are interested to use this crate for WebTransport. I'll look up for that a bit (I'm not aware of this :sweat_smile:).

If you think this might be useful and have the time to do this, feel free to open a tracking issue.

Thanks for the encouragements :smile:

**Comment by Pascualex** [comment]
I believe that no additional work is required to support WebTransport, but I might be wrong.

I just wanted to let you know because there might be more people looking for an HTTP/3 server from this point on 😄.
