### ISSUE TITLE
Frame stream (reader)

### ISSUE THREAD

**Issue by stammw** [hyperium/h3#9]
We want to poll a stream of [HTTP/3 frames] for the receiving ends of request streams, control stream and push streams. 

This is something I've already [implemented in `quinn-h3`]. This is based on `tokio_util::codec::FramedRead`, but will likely be easy to import and adapt to whatever solution we choose in #7 and #8. 

There is one point I'm not quite happy with though: the `DataFrame` partial handling. Here is how it works for now, imagine a response with a `2048` bytes body:

We recieve: `HeadersFrame(_) | DataFrame(payload { size: 2048 })`

```rust
let mut recv = FrameStream::new(recv_stream);

assert_matches!(recv.poll_next(cx).await, Some(Ok(HttpFrame::Headers(_))));

// Read the body
assert_matches!(
  recv.poll_next(cx).await,
  Some(Ok(HttpFrame::Data(DataFrame(b)))) if b.len() == 1024 // partial payload at the start (b: Bytes)
);
assert_matches!(
  recv.poll_next(cx).await,
  Some(Ok(HttpFrame::Data(DataFrame(b)))) if b.len() == 1024 // partial payload at the end
);

assert_matches!(recv.poll_next(cx).await, None); // No trailers
```

So as soon as there is some data available in the transport's buffer, it is yielded as a `Bytes` wrapped in a "fake" `DataFrame`. The problem here is that the user doesn't know what size the original `DataFrame` was. If we take a proxy use case, we will change the `DataFrame` sizes that we forward. If they are smaller than the original, that means we'll add one header for each of them.

What I have in mind is: 

```rust
let mut recv = FrameStream::new(recv_stream);

assert_matches!(recv.poll_next(cx).await, Some(Ok(HttpFrame::Headers(_))));

// Read the body
// iterate on "real" DataFrames
while let Some(Ok(HttpFrame::Data(ref mut payload))) = recv.poll_next(cx).await {
  // payload is a stream of bytes and the len of the original DataFrame
  assert_eq!(data.len(), 2048);
  assert_matches!(data.poll_data().await, Some(b) if b.len() == 1024); // b: Bytes
  assert_eq!(data.remaining(), 1024);
  assert_matches!(data.poll_data().await, Some(b) if b.len() == 1024); // b: Bytes
  assert_matches!(data.poll_data().await, None);
}

assert_matches(recv.poll_next(cx).await, None); // No trailers
```

[HTTP/3 frames]: https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-http-framing-layer
[implemented in `quinn-h3`]: https://github.com/djc/quinn/blob/master/quinn-h3/src/frame.rs

**Comment by quentusrex** [comment]
Was this issue resolved with the MR that references it? https://github.com/hyperium/h3/pull/14 Or is there still functionality outstanding?

**Comment by stammw** [comment]
Yes this can now be closed. Thank you!
